
import com.sun.glass.ui.Window;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MOHAMED SHABEER KP
 */
public class Main extends javax.swing.JFrame {

    String path;
     File file;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        selection_panel = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        select_button = new javax.swing.JButton();
        header_panel = new javax.swing.JPanel();
        file_name_label = new javax.swing.JLabel();
        main_table_panel = new javax.swing.JPanel();
        main_table_scroll_panel = new javax.swing.JScrollPane();
        main_table = new javax.swing.JTable();
        reg_selection_panel = new javax.swing.JPanel();
        reg_textfield = new javax.swing.JTextField();
        select_dropdown = new javax.swing.JComboBox<>();
        reg_button = new javax.swing.JButton();
        reg_dropdown_label = new javax.swing.JLabel();
        student_info_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        result_display_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_tabel = new javax.swing.JTable();
        submit_panel = new javax.swing.JPanel();
        submit_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(1700, 800));
        setSize(new java.awt.Dimension(1700, 800));

        selection_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        selection_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_label.setText("WELCOME TO THE SAMPLE APP");
        selection_panel.add(welcome_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        select_button.setText("SELECT CSV FILE");
        select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_buttonActionPerformed(evt);
            }
        });
        selection_panel.add(select_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 97, -1, -1));

        header_panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        header_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        file_name_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        file_name_label.setText("File Name");
        header_panel.add(file_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        main_table_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_table.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        main_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    main_table.getTableHeader().setReorderingAllowed(false);
    main_table_scroll_panel.setViewportView(main_table);

    main_table_panel.add(main_table_scroll_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 430));

    reg_selection_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    reg_selection_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    reg_textfield.setVisible(false);
    reg_selection_panel.add(reg_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 162, 32));

    select_dropdown.setVisible(false);
    select_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>());

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, reg_textfield, org.jdesktop.beansbinding.ELProperty.create("${text}"), select_dropdown, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
    bindingGroup.addBinding(binding);

    select_dropdown.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            select_dropdownActionPerformed(evt);
        }
    });
    reg_selection_panel.add(select_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 162, -1));

    reg_button.setVisible(false);
    reg_button.setText("Click here");
    reg_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            reg_buttonActionPerformed(evt);
        }
    });
    reg_selection_panel.add(reg_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 169, -1, -1));

    reg_dropdown_label.setVisible(false);
    reg_dropdown_label.setText("Identification no :");
    reg_selection_panel.add(reg_dropdown_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

    student_info_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel1.setText("Selected Student Information");
    student_info_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 292, 30));

    result_display_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    display_tabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    display_tabel.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {}
        },
        new String [] {

        }
    )
    {public boolean isCellEditable(int row, int column){return false;}}
    );
    display_tabel.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(display_tabel);

    result_display_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 70));

    submit_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    submit_button.setText("SUBMIT");
    submit_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            submit_buttonActionPerformed(evt);
        }
    });
    submit_panel.add(submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 200, 64));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(reg_selection_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addComponent(selection_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(student_info_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(result_display_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(main_table_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 9, Short.MAX_VALUE)))
                    .addContainerGap())
                .addComponent(submit_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(selection_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(reg_selection_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(main_table_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(student_info_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(result_display_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(submit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_buttonActionPerformed
        JFileChooser jfc = new JFileChooser(); 
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
                File selectedSourceFile = jfc.getSelectedFile();
                String fname=selectedSourceFile.getName();
                int typePos =fname.lastIndexOf(".");
                String ftype=fname.substring(typePos,fname.length());
               
                if(".csv".equals(ftype))
                {
                   file_name_label.setText(fname);
                   path=selectedSourceFile.getAbsolutePath();
                
                   file =new File(path);
        try {
           
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
             
            DefaultTableModel model =(DefaultTableModel)main_table.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();
           
            for(int i =0;i<tableLines.length;i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }
            } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                                   }
            reg_dropdown_label.setVisible(true);
            reg_textfield.setVisible(true);
            select_dropdown.setVisible(true);
            reg_button.setVisible(true);
                 }
                 else
                      JOptionPane.showMessageDialog(null, "Select A Valid CSV file", "Invalid File " , JOptionPane.INFORMATION_MESSAGE);
                
            DefaultTableModel model1 =(DefaultTableModel)main_table.getModel();
            String[] regArr =  new String[model1.getRowCount()];
            for(int i=0;i<model1.getRowCount();i++)
            {
                regArr[i] = String.valueOf(model1.getValueAt(i,0));
                select_dropdown.addItem(regArr[i]);
            }   

        }
    }//GEN-LAST:event_select_buttonActionPerformed

    private void reg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_buttonActionPerformed
        DefaultTableModel model1 =(DefaultTableModel)main_table.getModel();
        DefaultTableModel model2 =(DefaultTableModel)display_tabel.getModel();
        String regno = reg_textfield.getText();
        int flag=0;
        
        for(int i=0;i<model1.getRowCount();i++)
        {
        if(model1.getValueAt(i, 0) .equals(regno))
         {
                BufferedReader br;
            try {
                br = new BufferedReader(new FileReader(file));
                String firstLine = br.readLine().trim();
                String[] columnsName = firstLine.split(",");
                model2.setRowCount(0);
                model2.setColumnIdentifiers(columnsName);
                
                Object[] tableLines = br.lines().toArray();
       
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model2.addRow(dataRow);
            
                } catch (Exception ex) 
                {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
     
           flag=1;
         }
      
        }
        if(flag!=1)
                JOptionPane.showMessageDialog(null, "No match Found", " ERROR " , JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_reg_buttonActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void select_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_dropdownActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable display_tabel;
    private javax.swing.JLabel file_name_label;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable main_table;
    private javax.swing.JPanel main_table_panel;
    private javax.swing.JScrollPane main_table_scroll_panel;
    private javax.swing.JButton reg_button;
    private javax.swing.JLabel reg_dropdown_label;
    private javax.swing.JPanel reg_selection_panel;
    private javax.swing.JTextField reg_textfield;
    private javax.swing.JPanel result_display_panel;
    private javax.swing.JButton select_button;
    private javax.swing.JComboBox<String> select_dropdown;
    private javax.swing.JPanel selection_panel;
    private javax.swing.JPanel student_info_panel;
    private javax.swing.JButton submit_button;
    private javax.swing.JPanel submit_panel;
    private javax.swing.JLabel welcome_label;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
